config/routes.rb
Rails.application.routes.draw do

  api_version(:module => "V1", :path => {:value => "v1"}, :default => true) do
    resources :articulo
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_scope :usuario do
    delete "usuarios/sign_out" => "usuarios/sessions#destroy"
  end

  devise_for :usuarios, controllers: { passwords: "usuarios/passwords",
                                        sessions: "usuarios/sessions",
                                        registrations: "usuarios/registrations",
                                        omniauth_callbacks: "usuarios/omniauth_callbacks" }

  resources :articulos
  get :set_new_locale, to:'application#set_new_locale'
  get :enviar_sumario, to:'application#enviar_sumario'
  get :enviar_sumario_nuevos_usuarios, to: 'application#enviar_sumario_nuevos_usuarios'
  root to: 'welcome#index'


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_locale

  def index
  end
end

app/views/welcome/index.html.slim
.row
  .col-md-12
    h1.page-header Blog
  .col-md-1
	  = button_to t(:articulos), articulos_path, class: "button btn btn-default", method: :get
  .col-md-1
	  = button_to t(:nuevo), new_articulo_path, class: "button btn btn-default", method: :get
  .col-md-2
	  = button_to t(".diez_mails"), enviar_sumario_path, class: "button btn btn-default", method: :get
  .col-md-1
	  = button_to t(".diez_mails_cinco_usuarios"), "#", class: "button btn btn-default ajax", method: :get

.alert.alert-success.alert-mail
  | Procesando mensaje