config/routes.rb
Rails.application.routes.draw do

  api_version(:module => "V1", :path => {:value => "v1"}, :default => true) do
    resources :articulo
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_scope :usuario do
    delete "usuarios/sign_out" => "usuarios/sessions#destroy"
  end

  devise_for :usuarios, controllers: { passwords: "usuarios/passwords",
                                        sessions: "usuarios/sessions",
                                        registrations: "usuarios/registrations",
                                        omniauth_callbacks: "usuarios/omniauth_callbacks" }

  resources :articulos
  get :set_new_locale, to:'application#set_new_locale'
  get :enviar_sumario, to:'application#enviar_sumario'
  get :enviar_sumario_nuevos_usuarios, to: 'application#enviar_sumario_nuevos_usuarios'
  root to: 'welcome#index'


end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container
    .navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"]
      a.navbar-brand
        = link_to 'Blog', root_path, class: 'a navbar-brand'
    ul.nav.navbar-nav.navbar-right
      li
        a href=destroy_usuario_session_path
          button.btn.btn-default.btn-xs =t :cerrar_sesion
      li
        = button_to 'Español',set_new_locale_path('es'), class: 'btn button btn-default btn-xs', method: :get
      li
        = button_to 'English',set_new_locale_path('en'), class: 'btn button btn-default btn-xs', method: :get

app/views/layouts/application.html.slim
doctype html
html
  head
    title Blog
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    = render 'layouts/navbar'
    .container
      = yield