config/routes.rb
Rails.application.routes.draw do

  api_version(:module => "V1", :path => {:value => "v1"}, :default => true) do
    resources :articulo
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_scope :usuario do
    delete "usuarios/sign_out" => "usuarios/sessions#destroy"
  end

  devise_for :usuarios, controllers: { passwords: "usuarios/passwords",
                                        sessions: "usuarios/sessions",
                                        registrations: "usuarios/registrations",
                                        omniauth_callbacks: "usuarios/omniauth_callbacks" }

  resources :articulos
  get :set_new_locale, to:'application#set_new_locale'
  get :enviar_sumario, to:'application#enviar_sumario'
  get :enviar_sumario_nuevos_usuarios, to: 'application#enviar_sumario_nuevos_usuarios'
  root to: 'welcome#index'


end

app/models/articulo.rb
class Articulo < ActiveRecord::Base
  belongs_to :usuario
  paginates_per 50
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  def index
    # @articulos = Articulo.all
  end

  def new
  end

  def show
    @articulo = Articulo.find(params[:id])
  end

  def create
    @articulo = Articulo.new(articulo_params)
    @articulo.usuario_id = current_usuario.id
    @articulo.save
    redirect_to @articulo
  end

  def edit
    @articulo = Articulo.find(params[:id])
    authorize @articulo
  end

  def update
    @articulo = Articulo.find(params[:id])
    if @articulo.update_attributes(articulo_params)
      redirect_to :action => 'show' , :id => @articulo.id
    end
  end

  def destroy
    Articulo.find(params[:id]).destroy
    redirect_to :action => 'index'
  end

  private

  def articulo_params
    params.require(:articulo).permit(:titulo, :texto)
  end
end

app/controllers/v1/articulo_controller.rb
class V1::ArticuloController < V1::BaseController
  before_filter :find_articulo, only: [:update]


  def index
    render json: Articulo.order(id: :ASC).page(params[:pag])
  end

  def update
    if @articulo.update_attributes(articulo_params)
        render json: @articulo
    else
        render nothing: true, status: :bad_request
    end
  end

  def articulo_params
    params.require(:art).permit(:titulo, :texto)
  end

  private
   def find_articulo
     @articulo = Articulo.find(params[:id])
     render nothing: true, status: :not_found unless @articulo.present? && @articulo.usuario_id == current_usuario.id
   end
end

app/views/articulos/edit.html.slim
.row
	.col-md-12
		h1.page-header =t :nuevo_articulo_titulo

.row
	.col-md-6

		a href=articulos_path
			button.btn.btn-default =t :articulos


		= form_for :articulo, url: articulo_path(@articulo.id), method: :put do |f|

		  .form-group

		    p
			  = f.label t(:articulo_field_titulo)
		      = f.text_field :titulo, class: "form-control", value: @articulo.titulo

		  .form-group

		    p
		      = f.label t(:articulo_field_texto)
		      = f.text_area :texto, class: "form-control", value: @articulo.texto

		  .form-group

		    p
		      = f.submit t(:grabar), class: "btn-default btn"

app/views/articulos/index.html.slim
= hidden_field_tag(:ruta_api, v1_articulo_index_path)
= hidden_field_tag(:ruta_api_edit, v1_articulo_path(:id))

.row
	.col-md-12
		h1.page-header =t :lista_articulo_titulo

.row
	.col-md-12
		a href= new_articulo_path
			button.btn.btn-default =t :nuevo
		br
		table.table cellspacing=15 cellpadding=15
			thead
				tr
					th =t :articulo_field_titulo
					th =t :articulo_field_texto
					th =t :articulo_field_usuario
					th
					th
			tbody.contenido


div.form_edit
	= form_tag( '', :method => :put ,  class: 'form_tag_edit' ) do

		table.table cellspacing=15 cellpadding=15
			tr
				td
					= text_field_tag(:tit_art )
				td
					= text_field_tag(:txt_art )
				td
					= label_tag(:usuario, "Usuario", class: 'usu_art' )
		
		.btn.btn-default.btn-cancel-art type='button' =t :cancelar
		.btn.btn-success.btn-edit-art type='button' =t :grabar

app/views/articulos/new.html.slim
	.row
		.col-md-12
			h1.page-header =t :nuevo_articulo_titulo

	.row
		.col-md-6

			a href=articulos_path
				button.btn.btn-default =t :articulos


			= form_for :articulo, url: articulos_path do |f|

			  .form-group

			    p
				  = f.label t(:articulo_field_titulo)
			      = f.text_field :titulo, class: "form-control"

			  .form-group

			    p
			      = f.label t(:articulo_field_texto)
			      = f.text_area :texto, class: "form-control"

			  .form-group

			    p
			      = f.submit t(:grabar), class: "btn-default btn"

app/views/articulos/show.html.slim
	.row
		.col-md-12
			h1.page-header =t :show_articulo_titulo

	.row
		.col-md-12
			a href=articulos_path
				button.btn.btn-default =t :articulos

			BR

			p
			  strong =t :articulo_field_titulo

			blockquote
				p
			  		= @articulo.titulo

			p
			  strong =t :articulo_field_texto

			blockquote
				p
			  		= @articulo.texto